// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgh6W55Sobvv8Kjk__gAAEAjdbyLrkM9Q',
    appId: '1:981921788525:web:503ce8c275ad3f5d238564',
    messagingSenderId: '981921788525',
    projectId: 'food-delivery-15fb4',
    authDomain: 'food-delivery-15fb4.firebaseapp.com',
    storageBucket: 'food-delivery-15fb4.appspot.com',
    measurementId: 'G-GVLGJETZM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTHKB8j3Ief8jIwm9VmZPKIB7PiXA2MgQ',
    appId: '1:981921788525:android:af22c6382b05be0c238564',
    messagingSenderId: '981921788525',
    projectId: 'food-delivery-15fb4',
    storageBucket: 'food-delivery-15fb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr9yRfy9wv_Q08mNzGBTjRdvn-Ot_e-AM',
    appId: '1:981921788525:ios:cc147aafc5448355238564',
    messagingSenderId: '981921788525',
    projectId: 'food-delivery-15fb4',
    storageBucket: 'food-delivery-15fb4.appspot.com',
    iosClientId: '981921788525-dmp0erbdv5m1c2rqub845raanrcjgvpu.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodygo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr9yRfy9wv_Q08mNzGBTjRdvn-Ot_e-AM',
    appId: '1:981921788525:ios:cc147aafc5448355238564',
    messagingSenderId: '981921788525',
    projectId: 'food-delivery-15fb4',
    storageBucket: 'food-delivery-15fb4.appspot.com',
    iosClientId: '981921788525-dmp0erbdv5m1c2rqub845raanrcjgvpu.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodygo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgh6W55Sobvv8Kjk__gAAEAjdbyLrkM9Q',
    appId: '1:981921788525:web:610d41def5de082c238564',
    messagingSenderId: '981921788525',
    projectId: 'food-delivery-15fb4',
    authDomain: 'food-delivery-15fb4.firebaseapp.com',
    storageBucket: 'food-delivery-15fb4.appspot.com',
    measurementId: 'G-WGVHRC0XX7',
  );

}